Story-845: Migrate to Maven Central
REGnosys/rosetta-common pull request #364
Opened 2024-04-23 14:55 UTC by JayasriR

2024-04-24 10:29 UTC, ja6a-regnosys requested changes

2024-04-24 10:29 UTC, ja6a-regnosys commented on codefresh.yml
> +    image: maven:3.8.2-jdk-11
java 11? 17 was the old one

2024-04-24 10:29 UTC, ja6a-regnosys commented on pom.xml
> +        <maven.compiler.release>11</maven.compiler.release>
this could be a problem

2024-04-24 10:29 UTC, ja6a-regnosys commented on pom.xml
> +        <plugins>
poor layout - needs a tab indentation

2024-04-24 10:29 UTC, ja6a-regnosys commented on pom.xml
> +        </pluginManagement>
ditto

2024-04-24 10:47 UTC, ja6a-regnosys requested changes

2024-04-24 10:47 UTC, ja6a-regnosys commented on pom.xml
> +        <maven.compiler.release>11</maven.compiler.release>
why not keep it at 8?

2024-04-24 10:59 UTC, JayasriR commented on pom.xml
> +        <maven.compiler.release>11</maven.compiler.release>
Might has well upgrade to the latest?

2024-04-29 10:45 UTC, ja6a-regnosys approved these changes

2024-04-29 11:06 UTC, merged